
Epoch [1/10]
Traceback (most recent call last):
  File "/notebooks/s2_multiencoder/combined/main.py", line 122, in <module>
    main()
  File "/notebooks/s2_multiencoder/combined/main.py", line 81, in main
    best_ckpt = train_dual_encoder_probe(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/notebooks/s2_multiencoder/combined/train.py", line 68, in train_dual_encoder_probe
    for clip_imgs, dino_imgs, labels in train_pbar:
  File "/usr/local/lib/python3.11/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/notebooks/s2_multiencoder/combined/dataset.py", line 130, in dual_collate_fn
    dino_imgs = safe_stack(dino_list)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/notebooks/s2_multiencoder/combined/dataset.py", line 127, in safe_stack
    return torch.stack(valid_tensors, dim=0)
           ^^^^^
NameError: cannot access free variable 'torch' where it is not associated with a value in enclosing scope